version: '3'

services:
  postgresql:
    image: postgres
    container_name: groth
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=groth
      - POSTGRES_PASSWORD=groth
      - POSTGRES_DATABASE=groth
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-groth
    ports:
      - '6379-6379'






